SUPABASE_URL = "https://rnjepukxypluidotkeqq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuamVwdWt4eXBsdWlkb3RrZXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNTg4MDksImV4cCI6MjA4NTkzNDgwOX0.PRqILaNoRyIxQz-kW2lnWrCalwBxE2gkwsxzPiXjihw"
